name: Build ZIP for WP Playground
on:
  push:
    branches:
      - master

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Tworzymy folder dist z wykluczeniami
      - name: Prepare dist folder
        run: |
          mkdir -p dist
          rsync -av \
            --exclude='.github' \
            --exclude='README.md' \
            --exclude='scss' \
            --exclude='node_modules' \
            --exclude='dist' \
            ./ dist/

      # 3. Tworzymy ZIP
      - name: Create ZIP
        run: |
          cd dist
          zip -r ../basic-auracode.zip .
          cd ..

      # 4. Upload ZIP jako artefakt workflow
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: basic-auracode
          path: basic-auracode.zip