name: Build ZIP and Release
on:
  push:
    branches:
      - master

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Tworzymy folder dist i kopiujemy potrzebne pliki
      - name: Copy necessary files
        run: |
          mkdir dist
          rsync -av --exclude='scss' --exclude='.github' --exclude='README.md' ./ dist/

      # Tworzymy ZIP
      - name: Create ZIP
        run: |
          cd dist
          zip -r ../basic-auracode.zip .

      # Tworzymy tag automatycznie
      - name: Create Tag
        id: tag
        run: |
          TAG="v1.0.$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG

      # Publikujemy ZIP na GitHub Release
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: basic-auracode.zip
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
